### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 18

### ISSUE THREAD

**Issue by bebone** [bebone/dev-test#6]
**[in app/config/security.yml, line 18](https://github.com/bebone/dev-test/blob/65339c69d23c6445e458fb7e071a50e77c505221/app/config/security.yml#L18)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                     user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                     admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/2ed4ef6a-59ca-41b8-9dff-a274bd8de1e8/analyses/2)_
